# Generated by Django 5.2.4 on 2025-07-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_edit_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='pending_edits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='documentation',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
    
   
