# Generated by Django 5.2.4 on 2025-07-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_edit_pending_project_pending_edits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documentation',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_zip',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
