# Generated by Django 5.2.4 on 2025-07-22 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_wishlist_delete_wishlistrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='user',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='timestamp',
            new_name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='payment_status',
        ),
    ]
